# Generated by Django 4.2.23 on 2025-07-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('source_ip', models.GenericIPAddressField()),
                ('event_type', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
